"""add site_credentials table

Revision ID: f9024451f825
Revises: d041bbaef980
Create Date: 2026-10-08 19:31:02.843665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9024451f825'
down_revision: Union[str, Sequence[str], None] = 'd041bbaef980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('login_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_credentials_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_credentials_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_credentials_site_id'))
        batch_op.drop_index(batch_op.f('ix_site_credentials_expires_at'))

    op.drop_table('site_credentials')
    # ### end Alembic commands ###
